<?php


///**
// * Implements hook_node_load().
// */
function webform_calendar_date_format_node_load($nodes, $types)
{
    foreach($nodes as $single_node) {
        if (isset($single_node->webform)) {
//            dpm($single_node->webform, "node load");
            $module_path = drupal_get_path("module", "webform_calendar_date_format");
            drupal_add_js($module_path . "/js/webform_calendar_date_format.js");
            drupal_add_css($module_path . "/css/webform_calendar_date_format.css");
        }
    }
}

/**
 * Implements hook_menu().
 */
function webform_calendar_date_format_menu()
{
    $items['webform_calendar_date_format/format'] = [
        'type' => MENU_CALLBACK,
        'page callback' => 'webform_calendar_date_format_format',
        'access arguments' => ['access content'],
    ];
    return $items;
}

/**
 * Implements hook_help().
 */
function webform_calendar_date_format_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#webform_calendar_date_format":
      $output = "<p>Please read the readme.md file.</p>";
      break;
  }
  return $output;
}

/**
 * Format the date
 */
function webform_calendar_date_format_format()
{
    $answer = [];
    if (isset($_POST["year"], $_POST["month"], $_POST["day"])) {
        $year = $_POST["year"];
        $month = $_POST["month"];
        $day = $_POST["day"];
        $format = $_POST["format"];


        $formatType = $format;//short or medium or long
        $formatted = format_date(mktime(0, 0, 0, $month, $day, $year), $formatType);
        $formatted = preg_replace('/ - .*/', '', $formatted);

        $answer['formatted'] = $formatted;
    }
    drupal_json_output($answer);
    exit;
}