<?php

/**
 * Implements preprocess_html().
 */
function webform_calendar_date_format_preprocess_html(&$vars)
{
    $module_path = drupal_get_path("module", "webform_calendar_date_format");
    drupal_add_js($module_path . "/js/webform_calendar_date_format.js");
    drupal_add_css($module_path . "/css/webform_calendar_date_format.css");
}

/**
 * Implements hook_menu().
 */
function webform_calendar_date_format_menu()
{
    $items['webform_calendar_date_format/format'] = [
        'type' => MENU_CALLBACK,
        'page callback' => 'webform_calendar_date_format_format',
        'access arguments' => ['access content'],
    ];
    return $items;
}

/**
 * Implements hook_help().
 */
function webform_calendar_date_format_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#webform_calendar_date_format":
      $output = "<p>Please read the readme.md file.</p>";
      break;
  }
  return $output;
}

/**
 * Format the date
 */
function webform_calendar_date_format_format()
{
    $answer = [];
    if (isset($_POST["year"], $_POST["month"], $_POST["day"])) {
      $year = $_POST["year"];
      $month = $_POST["month"];
      $day = $_POST["day"];

      //@todo: make this an option
      $formatType= 'long';//short or medium or long
      $formatted = format_date(mktime(0, 0, 0, $month, $day, $year), $formatType);

      //remove hour:min - @todo: make this an option
      $formatted = preg_replace('/ - .*/', '', $formatted);

      $answer['formatted'] = $formatted;
    }
    drupal_json_output($answer);
    exit;
}